# Generated by Django 3.2.6 on 2021-08-22 15:03

import dj_ingredient_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', dj_ingredient_field.fields.IngredientField()),
            ],
        ),
    ]
